# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI & CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn 
    - run: yarn install
    - run: yarn docs:build
    
    - name: 📂 Sync files    
      uses: milanmk/actions-file-deployer@master
      with:
        remote-protocol: ${{ secrets.PROTOCOL }}
        remote-host: ${{ secrets.HOST }}
        remote-port: ${{ secrets.PORT }}
        remote-user: ${{ secrets.USER }}
        remote-password: ${{ secrets.PASSWORD }}
        sync: full
        local-path: docs/.vitepress/dist/
        remote-path: /usr/share/nginx/blog

